### ISSUE TITLE
Missing cert-manager-crds.json as referenced in https://blog.jetstack.io/blog/kustomize-cert-manager/

### ISSUE THREAD

**Issue by dcd000** [jetstack/kustomize-cert-manager-demo#2]
Hello.
Following referenced blog I can't find cert-manager-crds.json file in repo.
Thanks in advance.

**Comment by wwwil** [comment]
Hi! Thanks for the feedback 😄 I think I stopped using the `cert-manager-crds.json` file to specify custom resources in favour of `cert-manager-configuration.yaml` as the `crds` specification didn't seem to work. I think I then just forgot to update the YAML in the blog post. I will look into this today and confirm!

**Comment by wwwil** [comment]
Yeah I've confirmed that the `crds` field is not required, you can find more info in this [issue](https://github.com/kubernetes-sigs/kustomize/issues/480) and this [example](https://github.com/kubernetes-sigs/kustomize/tree/master/examples/transformerconfigs/crd). I've pushed an update to the blog post to remove the `crds` field so it matches the `overlays/cert-manager/kustomization.yaml` in this demo repo.
